id: 6fbce773a05146638afc4d734a8f1df8
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_515-Dharani_of_Buddha's_Essence-v2
  language: bo
  author: ''
  volume: {}
